source 'https://rubygems.org'

gem 'rspec'

# RuboCop is a Ruby static code analyzer and code formatter. Out of the box it will enforce many of the guidelines outlined in the community Ruby Style Guide.
# https://github.com/rubocop-hq/rubocop
gem 'rubocop', '~> 0.63.1', require: false